#!/usr/bin/env python3

import re
from sys import argv, stdin

def print_usage():
    """
    Print both ways of using the command
    """
    print("Usage:")
    print("{} <pattern> <string>".format(argv[0]))
    print("some_command | {} <pattern>".format(argv[0]))

def print_match(line, pattern):
    """
    Search `line` for matches of `pattern` and print the first
    capture group when they occur.  If no capture group, do nothing
    """
    match = re.search(pattern, line)
    if match is not None:
        result = match.groups()[0]
        print(result)


if len(argv)==2:
    """
    Match on stdin
    """
    _, pattern = argv
    for line in stdin:
        line=line.replace('\n','')
        print_match(line, pattern)
elif len(argv)==3:
    """
    Match on provided string
    """
    _, pattern, s = argv
    lines = s.split('\n')
    for line in lines:
        print_match(line, pattern)
else:
    """
    Incorrect number of arguments
    """
    print_usage()
    exit(1)